//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.14 at 11:14:37 AM CET 
//


package uima.sandbox.lexer.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uima.sandbox.tokenizer.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class SegmentFactory {

    private final static QName _Segments_QNAME = new QName("", "segments");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uima.sandbox.tokenizer.models
     * 
     */
    public SegmentFactory() {
    }

    /**
     * Create an instance of {@link Segment }
     * 
     */
    public Segment createSegment() {
        return new Segment();
    }

    /**
     * Create an instance of {@link Segments }
     * 
     */
    public Segments createSegments() {
        return new Segments();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Segments }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "segments")
    public JAXBElement<Segments> createSegments(Segments value) {
        return new JAXBElement<Segments>(_Segments_QNAME, Segments.class, null, value);
    }

}
